# Generated by Django 5.2.4 on 2025-10-12 18:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='registered_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
